services:
  tipserver:
    container_name: Tip-server
    image: tipserver
    restart: unless-stopped
    build: .
    networks: 
      - nginxproxymanager_default
    volumes:
      - ./:/app
    env_file:
      - .env
  
    ports:
      - "3550:4000"
    command: npm start
  
networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true

